services:
  bahninfo:
    image: niggiover9000/bahninfo:latest
    container_name: bahninfo
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .env:/app/.env
      - ./personal_data.py:/app/personal_data.py
      - ./ads.txt:/app/static/ads.txt