services:
  bahninfo:
    image: niggiover9000/bahninfo:latest
    container_name: bahninfo
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env