art = {
    "AA": "Abnehmeranlage",
    "Abzw": "Abzweigstelle",
    "Anst": "Anschlussstelle",
    "Awanst": "Ausweichanschlussstelle",
    "Bf": "Bahnhof",
    "Bft": "Bahnhofsteil",
    "Bft Abzw": "Bahnhofsteil Abzweigstelle",
    "Bk": "Blockstelle",
    "Bush": "Bushaltestelle",
    "BZ": "Betriebszentrale",
    "BZ N": "Betriebszentrale",
    "Dkst": "Deckungsstelle",
    "Est": "Einsatzstelle für Zugpersonal",
    "Fwst": "Fernwirkstelle",
    "Gp": "Grenzpunkt",
    "Hp": "Haltepunkt",
    "LGr": "Landesgrenze",
    "LW": "Laufweg",
    "Museum": "Museumsbahnhof",
    "Park": "Parkeisenbahn",
    "PDGr": "Produktionsdurchführungsgrenze",
    "RBGr": "Regionalbereichsgrenze",
    "Sbk": "Selbsttätige Blockstelle",
    "Schstr": "Schutzstrecke",
    "Slst": "Schiffslandestelle",
    "Sp": "Schaltposten",
    "Strw": "Streckenwechsel",
    "Sw": "Schaltwerk",
    "Tank": "Tankanlage",
    "Tp": "Tarifpunkt",
    "Urw": "Umrichterwerk",
    "Uw": "Unterwerk",
    "Üst": "Überleitstelle",
    "Werk": "Betriebswerk",
    "Zes": "Zentralschaltstelle"
}

region = {
    "A": "Hamburg",
    "B": "Berlin",
    "C": "Ausländische Örtlichkeiten von Schienengüterverkehrsunternehmen",
    "D": "Dresden",
    "E": "Essen",
    "F": "Frankfurt",
    "H": "Hannover",
    "I": "Ortsfeste und ortsveränderliche Energieanlagen der 16,7-Hertz-Energieversorgung",
    "J": "Ausländische Örtlichkeiten von Schienengüterverkehrsunternehmen",
    "K": "Köln",
    "L": "Halle",
    "M": "München",
    "N": "Nürnberg",
    "O": "Ausländische Örtlichkeiten in Ländern, die vollständig in das Europäische Fahrplanzentrum eingebunden sind",
    "P": "Ausländische Örtlichkeiten in Ländern, die vollständig in das Europäische Fahrplanzentrum eingebunden sind",
    "Q": "Örtlichkeiten von 50-Hertz-Anlagen",
    "R": "Karlsruhe",
    "S": "Saarbrücken",
    "T": "Stuttgart",
    "U": "Erfurt",
    "V": "Tankanlagen für Verbrennungsfahrzeuge",
    "W": "Schwerin",
    "X": "Ausland",
    "Y": "Streckenwechsel",
    "Z": "Ausland"}

sonderart = {
    "NE-": "Nichtbundeseigene Eisenbahn: ",
    "vp-": "verpachtet, "
}

''' 
Quelle: https://www.deutschebahn.com/resource/blob/5667426/c5a6eb32c2b78dc5b6c193e43add96ec/INBP_gueltig-ab-01-01-2021-data.pdf
Niedrigste Kategorie: 7
Höchste Kategorie: 1
Bahnhöfe einer höheren Kategorie weisen die Leistungen der niedrigeren Kategorien auf.
'''

bahnhofskategorien = {
    6: ["Sitzgelegenheit", "Wetterschutz"],
    5: ["Bahnhofsuhr/Zeitangabe",
        "Dynamische Reisendeninformation (visuell und/oder akustisch) mit Informationen zu Fahrplanabweichungen"],
    4: [],
    3: ["Dynamische Reisendeninformation (visuell und/oder akustisch) mit Informationen zum Fahrplan"],
    2: ["Servicemitarbeiter (auch zeitweise)", "Bahnsteigabschnittsmarkierung"],
    1: ["DB Information"]

}

betriebszustände = {"Planung": "", "Betrieb": "", "a.B.": "außer Betrieb", "ehemals": "", "Studie": ""}

betriebsstellen = {"AA": ["Abnehmeranlage", "", ""],
                   "Abzw": ["Abzweigstelle",
                            "Blockstelle der freien Strecke, wo Züge von einer Strecke auf eine andere Strecke übergehen können.",
                            ""],
                   "Anst": ["Anschlussstelle",
                            "Bahnanlage der freien Strecke, wo Züge ein angeschlossenes Gleis als Rangierfahrt befahren können, ohne dass die Blockstrecke für einen anderen Zug freigegeben wird.",
                            ""],
                   "Awanst": ["Ausweichanschlussstelle",
                              "Anschlußstelle, bei der die Blockstrecke für einen anderen Zug freigegeben werden kann.",
                              ""],
                   "Bf": ["Bahnhof",
                          "Bahnanlage mit mindestens einer Weiche, wo Züge beginnen, enden, ausweichen oder wenden dürfen.",
                          "Als Grenze zwischen den Bahnhöfen und der freien Strecke gelten im allgemeinen die Einfahrsignale oder Trapeztafeln, sonst die Einfahrweichen."],
                   "Bft": ["Bahnhofsteil",
                           "Teil einer Bahnanlage mit mindestens einer Weiche, wo Züge beginnen, enden, ausweichen oder wenden dürfen.",
                           "Siehe Bahnhof."],
                   "Bft Abzw": ["Bahnhofsteil Abzweigstelle",
                                "Bahnhofsteil, der zugleich eine Abzweigstelle ist.",
                                "Siehe Bahnhofsteil und Abzweigstelle."],
                   "Bk": ["Blockstelle",
                          "Bahnanlage, die eine Blockstrecke begrenzt.",
                          "Eine Blockstelle kann zugleich als Bahnhof, Abzweigstelle, Überleitstelle, Anschlußstelle, Haltepunkt, Haltestelle oder Deckungsstelle eingerichtet sein."],
                   "Bush": ["Bushaltestelle", "Haltestelle für den öffentlichen Straßenpersonenverkehr.", ""],
                   "BZ": ["Betriebszentrale", "Dispositions- und Notfallzentrale der Deutschen Bahn AG.", ""],
                   "Dkst": ["Deckungsstelle",
                            "Bahnanlage der freien Strecke, die den Bahnbetrieb insbesondere an beweglichen Brücken, Kreuzungen von Bahnen, Gleisverschlingungen und Baustellen sichert.",
                            ""],
                   "Est": ["Einsatzstelle für Zugpersonal", "Ort, an dem Zugpersonal den Dienst antritt oder beendet.",
                           ""],
                   "Fwst": ["Fernwirkstelle",
                            "Technische Einrichtung zur Fernsteuerung und Überwachung von bahnbetrieblichen Anlage.n",
                            ""],
                   "Gp": ["Grenzpunkt",
                          "Punkt auf freier Strecke, der die Betriebsgrenze zwischen zwei Eisenbahninfrastrukturunternehmen markiert.",
                          ""],
                   "Hp": ["Haltepunkt",
                          "Bahnanlage ohne Weichen, wo Züge planmäßig halten, beginnen oder enden dürfen.", ""],
                   "LGr": ["Landesgrenze", "", ""],
                   "LW": ["Laufweg", "", ""],
                   "Museum": ["Museumsbahnhof", "Bahnhof, der nicht mehr dem regulären Bahnverkehr dient.",
                              "Wird für museale Zwecke erhalten und ggf. mit historischen Fahrzeugen betrieben."],
                   "Park": ["Parkeisenbahn", "", ""],
                   "PDGr": ["Produktionsdurchführungsgrenze", "", ""],
                   "RBGr": ["Regionalbereichsgrenze",
                            "Betriebliche Grenze zwischen zwei Regionalbereichen innerhalb der Organisation der DB InfraGO.",
                            ""],
                   "Sbk": ["Selbsttätige Blockstelle",
                           "Bahnanlage, die eine Blockstrecke begrenzt, aber automatisch arbeitet, ohne dass ein Fahrdienstleiter eingreifen muss.",
                           "Siehe Blockstelle."],
                   "Schstr": ["Schutzstrecke",
                              "Abschnitt im Fahrleitungsnetz mit abgeschalteter oder elektrisch isolierter Stromversorgung.",
                              ""],
                   "Slst": ["Schiffslandestelle", "Ort, an dem ein Schiff an- und ablegen kann.", ""],
                   "Sp": ["Schaltposten", "Einrichtung, die zur Verteilung und Steuerung des Bahnstroms dient.", ""],
                   "Strw": ["Streckenwechsel", "Punkt, an dem ein Zug von einer Strecke auf eine andere übergeht", ""],
                   "Sw": ["Schaltwerk", "Einrichtung, die zur Verteilung und Steuerung des Bahnstroms dient.", ""],
                   "Tp": ["Tarifpunkt", "Bahnbetrieblicher Punkt zur tariflichen Abrechnung von Verkehrsleistungen",
                          ""],
                   "TrSt": ["Trennstelle", "Bahnanlage, die eine Trennstelle im Fahrleitungsnetz darstellt.", ""],
                   "Urw": ["Umrichterwerk", "Anlage zur Umwandlung von elektrischer Energie.", ""],
                   "Uw": ["Unterwerk",
                          "Bahneigene Stromversorgungsanlage, die die Oberleitung mit der benötigten Spannung und Frequenz versorgt.",
                          ""],
                   "Üst": ["Überleitstelle",
                           "Blockstelle der freien Strecke, wo Züge auf ein anderes Gleis derselben Strecke übergehen können.",
                           ""],
                   "Zes": ["Zentralschaltstelle", "", ""],
                   "NE-Bf": ["Nichtbundeseigene Eisenbahn: Bahnhof",
                             "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.", "Siehe Bahnhof."],
                   "NE-Bft": ["Nichtbundeseigene Eisenbahn: Bahnhofsteil",
                              "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.", "Siehe Bahnhofsteil."],
                   "NE-Bft Abzw": ["Nichtbundeseigene Eisenbahn: Bahnhofsteil Abzweigstelle",
                                   "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.",
                                   "Siehe Bahnhofsteil und Abzweigstelle."],
                   "NE-Bk": ["Nichtbundeseigene Eisenbahn: Blockstelle",
                             "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.",
                             "Siehe Blockstelle."],
                   "NE-Dkst": ["Nichtbundeseigene Eisenbahn: Deckungsstelle",
                               "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.",
                               "Siehe Deckungsstelle."],
                   "NE-Gp": ["Nichtbundeseigene Eisenbahn: Grenzpunkt",
                             "Punkt auf freier Strecke, der die Betriebsgrenze zwischen zwei Eisenbahninfrastrukturunternehmen markiert.",
                             "Siehe Grenzpunkt."],
                   "NE-Hp": ["Nichtbundeseigene Eisenbahn: Haltepunkt",
                             "Bahnanlage, die nicht im Eigentum der Deutschen Bahn AG steht.",
                             "Siehe Haltepunkt."],
                   "vp-Abzw": ["Verpachtete Abzweigstelle",
                               "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                               "Siehe Abzweigstelle."],
                   "vp-Anst": ["Verpachtete Abschlussstelle",
                               "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                               "Siehe Anschlussstelle."],
                   "vp-Awanst": ["Verpachtete Ausweichanschlussstelle",
                                 "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                                 "Siehe Ausweichanschlussstelle."],
                   "vp-Bf": ["Verpachteter Bahnhof",
                             "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                             "Siehe Bahnhof."],
                   "vp-Bft": ["Verpachteter Bahnhofsteil",
                              "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                              "Siehe Bahnhofsteil."],
                   "vp-Bft Abzw": ["Verpachteter Bahnhofsteil Abzweigstelle",
                                   "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                                   "Siehe Bahnhofsteil und Abzweigstelle."],
                   "vp-Bk": ["Verpachtete Blockstelle",
                             "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                             "Siehe Blockstelle."],
                   "vp-Hp": ["Verpachteter Haltepunkt",
                             "Bahnanlage, die im Eigentum der Deutschen Bahn AG steht, aber an Dritte verpachtet ist.",
                             "Siehe Haltepunkt."]
                   }

licenses = {"python-dotenv": ["BSD-3-Clause", "1.1.1", "Saurabh Kumar und Mitwirkende"],
            "requests": ["Apache-2.0", "2.32.4", "Kenneth Reitz und Mitwirkende"],
            "Flask": ["BSD-3-Clause", "3.1.1", "Pallets Project"],
            "waitress": ["Zope Public License 2.1", "3.0.2", "Zope Foundation und Mitwirkende"],
            "pandas": ["BSD-3-Clause", "2.3.1", "Pandas Development Team"],
            "urllib3": ["MIT License", "2.5.0", "urllib3-Entwickler"],
            "openpyxl": ["MIT License", "3.1.5", "openpyxl-Entwickler"],
            "flask_sitemap": ["MIT License", "0.4.0", "Sergio Oliveira"],
            "flask_caching": ["BSD-3-Clause", "2.3.1", "Flask-Caching-Entwickler"],
            "flask_mail": ["BSD-3-Clause", "0.10.0", "Dan Jacob"]}
