name: Build and Push Railquery to Docker Hub with Version Tag

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Versionsnummer lesen
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: In Docker Hub einloggen
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image bauen und pushen (latest + Version)
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/bahninfo
          VERSION=${{ steps.version.outputs.version }}

          docker build -t $IMAGE:latest -t $IMAGE:$VERSION .
          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION
